name: container
on: push


# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer
# xyz

jobs:
  terraform-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    container:
      image: docker.io/nhostert/myapp:terraform
    
